#!/usr/bin/env bash
#
#The MIT License (MIT)
#
#Copyright (c) 2014 Research Compendia
#
#Permission is hereby granted, free of charge, to any person obtaining a copy
#of this software and associated documentation files (the "Software"), to deal
#in the Software without restriction, including without limitation the rights
#to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the Software is
#furnished to do so, subject to the following conditions:
#
#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.
#
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.


# This script calls the author's LDA.R and sLDA.R scripts wih no ability to
# change parameters at this time.

set -e


function figure_3() {
    echo "generating figure 3"
    Rscript LDA.R
    if [ -f Rplots.pdf ]; then
        mv Rplots.pdf compendiaoutput/figure_3.pdf
    fi
}

function figure_4() {
    echo "generating figure 4"
    Rscript sLDA.R
    if [ -f Rplots.pdf ]; then
        mv Rplots.pdf compendiaoutput/figure_4.pdf
    fi
}

mkdir -p compendiaoutput

# default all
if [ -z "$1" ]; then
    figure_3
    figure_4
else
    case "$1" in
        3) figure_3;;
        4) figure_4;;
        *) figure_3; figure_4;
    esac
fi
